/* Brasília na Porrada 4.0 — deterministic combat core, 60 Hz. No dependencies. */
'use strict';
const Combat=(()=>{
const DT=1/60,GROUND=448;
const styles=[
 {speed:214,reach:14,wind:1.02,recover:1.10,role:'Controle de distância',strong:'Maior alcance nos golpes.',weak:'Recuperação lenta ao errar.',tip:'Mantenha o rival na ponta do chute.'},
 {speed:210,reach:0,wind:.90,recover:1.16,role:'Pressão e sequências',strong:'Golpes começam mais rápido.',weak:'Erros deixam uma abertura maior.',tip:'Emende os socos só quando acertar.'},
 {speed:230,reach:1,wind:1,recover:1.13,advance:12,role:'Avanço ofensivo',strong:'Golpes no chão avançam.',weak:'Demora para recuperar de ataques.',tip:'Pressione, mas não ataque no vazio.'},
 {speed:196,reach:4,wind:1.08,recover:1.03,parry:.14,guardRegen:21,guardUse:.88,role:'Defesa e punição',strong:'Defesa perfeita mais tolerante.',weak:'Mais lento para andar e atacar.',tip:'Defenda no timing e responda com soco.'},
 {speed:258,reach:-13,wind:.95,recover:.88,role:'Mobilidade e fintas',strong:'Mais rápido; recupera cedo.',weak:'Menor alcance dos golpes.',tip:'Entre, ataque e saia do alcance rival.'},
 {speed:204,reach:-9,wind:.93,recover:1.06,damage:2,role:'Força na curta distância',strong:'+2 de dano nos golpes no chão.',weak:'Curto alcance e pouca velocidade.',tip:'Aproxime-se com defesa; pressione perto.'},
 {speed:208,reach:11,wind:1.10,recover:1.13,role:'Alcance e pressão',strong:'Segundo maior alcance.',weak:'Preparação e recuperação lentas.',tip:'Faça o rival errar antes de discursar.'},
 {speed:244,reach:-7,wind:.97,recover:.93,counter:1.25,role:'Agilidade e contra-ataque',strong:'Contra-ataques com bônus de 25%.',weak:'Precisa chegar perto para acertar.',tip:'Interrompa golpes anunciados pelo rival.'}
];
const specials=[
 {damage:34,wind:.44,strike:.23,recover:.62,chase:560,hits:2,sequence:.28,push:340,desc:'Papelada e golpe final · 2 impactos'},
 {damage:36,wind:.50,strike:.24,recover:.70,chase:555,hits:2,sequence:.32,push:410,desc:'Duas metas, dois impactos · 2 impactos'},
 {damage:34,wind:.48,strike:.23,recover:.64,chase:650,hits:1,sequence:0,push:560,desc:'Arrancada sonora · grande empurrão'},
 {damage:40,wind:.64,strike:.26,recover:.86,chase:530,hits:1,sequence:0,push:450,desc:'Carimbada pesada · preparação longa'},
 {damage:30,wind:.34,strike:.21,recover:.54,chase:690,hits:1,sequence:0,push:390,desc:'Voadora veloz · menor dano'},
 {damage:38,wind:.58,strike:.25,recover:.78,chase:550,hits:2,sequence:.40,push:430,desc:'Abraço e queda · 2 impactos'},
 {damage:36,wind:.56,strike:.25,recover:.74,chase:570,hits:3,sequence:.44,push:410,desc:'Discurso e última palavra · 3 impactos'},
 {damage:32,wind:.38,strike:.22,recover:.58,chase:665,hits:3,sequence:.32,push:400,desc:'Giro e finalização · 3 impactos'}
];
const ladderDifficulty=stage=>[0,.5,1,1.5,2][Math.max(0,Math.min(4,stage))];
const aiProfile=d=>({reaction:.34-.075*d,decision:.30-.075*d,jitter:.20-.05*d,defend:.20+.24*d,combo:.12+.39*d});
const moves={
 jab:{wind:.09,active:.085,recover:.17,damage:7,reach:131,stun:.24,push:70,cost:7,pose:1,level:'mid'},
 cross:{wind:.11,active:.085,recover:.21,damage:9,reach:144,stun:.27,push:80,cost:9,pose:1,level:'mid'},
 kick:{wind:.21,active:.11,recover:.27,damage:14,reach:190,stun:.32,push:225,cost:15,pose:2,level:'mid'},
 finisher:{wind:.16,active:.1,recover:.32,damage:17,reach:185,stun:.38,push:360,cost:19,pose:2,level:'mid'},
 upper:{wind:.2,active:.13,recover:.39,damage:17,reach:143,stun:.4,push:125,lift:550,cost:20,pose:1,level:'high'},
 air:{wind:.1,active:.15,recover:.23,damage:12,reach:172,stun:.28,push:155,cost:11,pose:2,level:'air'},
 heavy:{wind:.39,active:.14,recover:.44,damage:25,reach:183,stun:.45,push:420,cost:24,pose:2,break:53,level:'mid'},
 special:{wind:.33,active:.16,recover:.43,damage:27,reach:220,stun:.45,push:360,cost:0,pose:1,level:'mid'}
};
function fighter(id,x,dir){return{id,x,y:0,vy:0,vx:0,dir,attackSerial:0,capturedBy:null,hp:140,guard:100,stamina:100,meter:0,stun:0,down:0,inv:0,dodge:0,dodgeCD:0,parryCD:0,parry:0,block:false,action:null,buffer:null,combo:0,comboDamage:0,comboTimer:0,hitChain:0,chainTimer:0,counter:0,move:0,flash:0,trail:0,wallLock:0,charge:0,stats:{hits:0,parries:0,dodges:0,maxCombo:0,damage:0,counters:0}}}
class Match{
 constructor(a=0,b=1,{difficulty=1,seed=1,training=false,multiplayer=false,roundSeconds=60,specials=true,introSeconds=4.2}={}){this.seed=seed>>>0;this.difficulty=Math.max(0,Math.min(2,difficulty));this.brains=[0,1].map(()=>({samples:[],sampleAt:-1,clock:.1,guard:0,move:0,feint:0,lastSerial:-1,history:[]}));this.training=training;this.multiplayer=multiplayer;this.otherInput={left:false,right:false,guard:false};this.f=[fighter(a,280,1),fighter(b,680,-1)];this.untimed=roundSeconds===0;this.specials=specials;this.time=this.untimed?0:roundSeconds;this.t=0;this.freeze=0;this.events=[];this.shots=[];this.over=false;this.winner=null;this.overtime=false;this.aiClock=.55;this.aiBlock=0;this.aiMove=0;this.input={left:false,right:false,guard:false};this.lastTap=[-9,-9];this.introDuration=introSeconds;this.intro=introSeconds;this.roundDamage=[0,0]}
 random(){this.seed=(Math.imul(this.seed,1664525)+1013904223)>>>0;return this.seed/4294967296}
 emit(type,data={}){this.events.push({type,...data})}
 clear(){this.input.left=this.input.right=this.input.guard=false;this.f.forEach(f=>{f.block=false;f.buffer=null;f.charge=0})}
 command(i,key){if(!this.specials&&(key==='special'||key==='burst'))return false;if(this.over||this.intro>0)return false;const f=this.f[i];if(f.capturedBy!==null)return false;if(key==='jump'){if(f.y===0&&!f.action&&f.stun<=0&&!f.down&&!f.dodge&&f.stamina>=8){f.vy=690;f.stamina-=8;f.block=false;f.vx=(this.multiplayer||i===0?(+(i===0?this.input:this.otherInput).right)-(+(i===0?this.input:this.otherInput).left):f.dir)*170;this.emit('jump',{i});return true}return false}
 if(key==='dodge'){if(f.y===0&&f.stun<=0&&!f.down&&!f.action&&f.dodgeCD<=0&&f.stamina>=28){let d=this.multiplayer||i===0?((+(i===0?this.input:this.otherInput).right)-(+(i===0?this.input:this.otherInput).left))||-f.dir:-f.dir;f.dodge=.24;f.inv=.19;f.vx=d*640;f.stamina-=28;f.dodgeCD=.78;f.block=false;this.emit('dodge',{i});return true}return false}
 if(key==='burst'){if(f.meter>=100&&(f.stun>0||f.down>0)){f.meter=0;f.stun=0;f.down=0;f.inv=.38;const o=this.f[1-i];if(Math.abs(f.x-o.x)<230){o.vx=f.dir*520;o.stun=.32;o.action=null}this.emit('burst',{i});return true}return false}

 if(f.stun>0||f.down>0||f.dodge>0){f.buffer={key,ttl:.14};return false}
 if(f.action){const ac=f.action;if(ac.name==='special')return false;if(ac.connected&&ac.t>=ac.m.wind+ac.m.active&&ac.t<ac.total&&ac.name==='jab'&&key==='punch')return this.begin(i,'cross');if(ac.connected&&ac.t>=ac.m.wind+ac.m.active&&ac.name==='cross'&&key==='kick')return this.begin(i,'finisher');if(ac.connected&&ac.t>=ac.m.wind+ac.m.active&&key==='special')return this.begin(i,'special');f.buffer={key,ttl:.16};return false}
 let name=key==='punch'?'jab':key==='kick'?'kick':key==='upper'?'upper':key==='heavy'?'heavy':key==='special'?'special':null;if(!name)return false;if(f.y>6&&name!=='special')name='air';if(f.y>6&&name==='special')return false;return this.begin(i,name)}
 begin(i,name){if(name==='special'&&!this.specials)return false;const f=this.f[i];let m={...moves[name]};const st=styles[f.id];if(name!=='special'){m.wind*=st.wind;m.recover*=st.recover;m.damage+=name==='air'?0:st.damage||0;}if(name==='special'){if(f.meter<100)return false;f.meter=0;m={...m,...specials[f.id],active:.16,reach:122,stun:1.1,pose:f.id===1||f.id===4?2:1,grab:false};this.emit('special',{i,id:f.id})}
 if(f.stamina<m.cost){this.emit('tired',{i});return false}f.stamina-=m.cost;f.attackSerial++;if(st.advance&&f.y===0&&name!=='special'){const gap=Math.abs(f.x-this.f[1-i].x);f.x+=f.dir*Math.min(st.advance,Math.max(0,gap-65));}f.block=false;f.charge=0;f.buffer=null;f.action={name,m,t:0,total:m.wind+m.active+m.recover,hit:false,hit2:false,connected:false,spawned:false,phase:name==='special'?'intro':null,phaseTime:0};return true}
 setBlock(i,v){const f=this.f[i];if(f.capturedBy!==null){f.block=false;return;}if(v&&!f.block&&(f.y===0||this.f[1-i].action?.name==='special')&&!f.action&&f.stun<=0&&!f.down&&(!f.dodge||this.f[1-i].action?.name==='special')&&f.guard>4){f.block=true;if(f.parryCD<=0){f.parry=styles[f.id].parry||.115;f.parryCD=.55}}else if(!v)f.block=false}
 ai(dt){this.controlAI(1,dt)}
 controlAI(i,dt=DT){if(this.training||this.over||this.intro>0)return;const f=this.f[i],op=this.f[1-i],d=this.difficulty,profile=aiProfile(d),s=this.brains[i],input=i===0?this.input:this.otherInput;
 // Only observable fighter state enters this delayed perception queue. Never inspect opponent input.
 if(s.sampleAt!==this.t){s.sampleAt=this.t;const a=op.action;s.samples.push({at:this.t,x:op.x,y:op.y,hp:op.hp,block:op.block,action:a?{name:a.name,t:a.t,wind:a.m.wind,active:a.m.active,total:a.total,serial:op.attackSerial}:null})}
 while(s.samples.length>1&&s.samples[1].at<=this.t-profile.reaction)s.samples.shift();const seen=s.samples[0];if(!seen||seen.at>this.t-profile.reaction){input.left=input.right=input.guard=false;f.move=0;return}
 const a=seen.action,dist=Math.abs(seen.x-f.x),dir=seen.x>=f.x?1:-1,reach=131+styles[f.id].reach;
 if(a&&a.serial!==s.lastSerial){s.lastSerial=a.serial;s.history.push(a.name);if(s.history.length>5)s.history.shift()}
 s.clock-=dt;s.guard=Math.max(0,s.guard-dt);s.feint=Math.max(0,s.feint-dt);let move=s.move;input.guard=s.guard>0;this.setBlock(i,input.guard);
 if(s.clock<=0){s.clock=profile.decision+this.random()*profile.jitter;s.move=dist>reach-8?dir:dist<80?-dir:0;const r=this.random();
 if(f.capturedBy!==null||f.stun>0||f.down>0){s.move=0}
 else if(f.stamina<26){s.move=-dir;if(dist<230&&r<.3+d*.2)s.guard=.18}
 else if(f.action){if(f.action.connected&&f.action.name==='jab'&&r<profile.combo)this.command(i,'punch');else if(d>=.75&&f.action.connected&&f.action.name==='cross'&&r<profile.combo)this.command(i,'kick');s.move=0}
 else if(a&&dist<250&&(a.name==='special'||a.t<a.wind+a.active)&&r<profile.defend){s.guard=.22+this.random()*.14;s.move=0;this.emit('aiDecision',{i,kind:'defend',observedAt:seen.at});}
 else if(d>=1.5&&s.history.length>=3&&s.history.slice(-3).every(n=>n===s.history.at(-1))&&dist<190&&r<.32){s.guard=.20;s.move=-dir;this.emit('aiDecision',{i,kind:'adapt',observedAt:seen.at});}
 else if(d>=.5&&a&&a.name!=='special'&&a.t>=a.wind+a.active&&dist<190+styles[f.id].reach){this.command(i,dist<reach?'punch':'kick');this.emit('aiDecision',{i,kind:'punish',observedAt:seen.at});}
 else if(d<.5&&r<.18){s.move=0;s.clock+=.18}
 else if(f.meter>=100&&this.specials&&dist<310&&r<.22+d*.12&&!seen.block){this.command(i,'special')}
 else if(seen.y>35&&dist<145+styles[f.id].reach&&d>=.5){this.command(i,'upper')}
 else if(d>=1.5&&dist>170&&dist<270&&r<.20){s.feint=.20;s.move=-dir;this.emit('aiDecision',{i,kind:'feint',observedAt:seen.at})}
 else if(dist<reach+(d<.5?12:0)){this.command(i,r<.68?'punch':r<.88?'kick':'heavy')}
 else if(dist<190+styles[f.id].reach&&r<.65){this.command(i,'kick')}
 else if(dist>180&&dist<300&&r>.88&&d>=.5){this.command(i,'jump')}
 if(f.guard<22){s.guard=0;s.move=-dir}if((f.x<90&&s.move<0)||(f.x>870&&s.move>0))s.move=dir;
 }
 move=s.feint>0?-dir:s.move;input.left=move<0;input.right=move>0;input.guard=s.guard>0;f.move=move;this.setBlock(i,input.guard);
 }
 damage(i,j,m,name,scale=1){const a=this.f[i],b=this.f[j];if(name!=='special'&&(b.inv>0||b.down>0)){this.emit('evade',{i:j});return false}if(b.counter>0){b.counter=0;b.action=null;a.action=null;a.hp=Math.max(0,a.hp-29);a.stun=.5;a.vx=-a.dir*370;b.stats.damage+=29;this.roundDamage[j]+=29;this.freeze=.085;this.emit('counter',{i:j,x:a.x,y:a.y});return false}
 if(b.block&&!m.grab){if(b.parry>0){b.parry=0;a.action=null;a.stun=.52;a.vx=-a.dir*160;b.meter=Math.min(100,b.meter+15);b.stamina=Math.min(100,b.stamina+15);b.stats.parries++;this.freeze=.09;this.emit('parry',{i:j,x:b.x,y:b.y});return false}b.guard=Math.max(0,b.guard-(m.break||m.damage*1.6)*(styles[b.id].guardUse||1));b.vx=a.dir*80;b.stamina=Math.max(0,b.stamina-3);a.meter=Math.min(100,a.meter+(name==='special'?0:1));this.freeze=.025;this.emit('block',{i:j,x:b.x,y:b.y});if(b.guard<=0){b.block=false;b.stun=.85;b.action=null;this.emit('guardbreak',{i:j})}return false}
 let counter=!!b.action&&(b.action.name==='special'||b.action.t<b.action.m.wind),chain=b.stun>0&&a.comboTimer>0;if(!m.follow){a.combo=chain?a.combo+1:1;a.comboDamage=chain?a.comboDamage:0;}let scaling=Math.max(.48,1-(a.combo-1)*.12);let dmg=Math.min(b.hp,m.fixedDamage??Math.round(m.damage*scaling*scale*(counter?(styles[a.id].counter||1.15):1)));if(counter&&!m.follow)a.stats.counters++;if(b.action?.name==='special')this.emit('specialInterrupted',{i:j,by:i});b.hp=Math.max(0,b.hp-dmg);a.comboDamage+=dmg;a.comboTimer=1.1;a.stats.hits++;a.stats.damage+=dmg;a.stats.maxCombo=Math.max(a.stats.maxCombo,a.combo);this.roundDamage[i]+=dmg;b.action=null;b.buffer=null;b.counter=0;b.block=false;b.stun=m.stun;b.flash=.12;b.vx=a.dir*m.push;b.vy=m.lift||b.vy;if(m.lift)b.y=Math.max(b.y,1);if(name!=='special'){a.meter=Math.min(100,a.meter+9);b.meter=Math.min(100,b.meter+5)}else if(!m.follow)b.meter=Math.min(100,b.meter+8);if(a.action)a.action.connected=true;
 if(name==='heavy'||name==='finisher'||name==='special'&&m.final!==false){b.down=name==='special'?1.08:.42;b.stun=name==='special'?1.12:.62;b.vy=name==='special'?460:250;b.y=Math.max(b.y,1)}this.freeze=name==='jab'?.045:name==='special'?(m.final===false?.055:.1):.075;this.emit('hit',{i,j,x:b.x,y:b.y,damage:dmg,combo:a.combo,total:a.comboDamage,counter,heavy:!['jab','cross','air'].includes(name),name,follow:!!m.follow});return true}
 advanceSpecial(i,dt,intents){const f=this.f[i],o=this.f[1-i],a=f.action,m=a.m;a.t+=dt;a.phaseTime+=dt;f.dir=o.x>=f.x?1:-1;f.vx=0;
 if(a.phase==='intro'){if(a.phaseTime>=m.wind){a.phase='chase';a.phaseTime=0}}
 else if(a.phase==='chase'){let gap=Math.abs(f.x-o.x);let speed=m.chase;if(f.id===1)speed*=.85+.3*Math.abs(Math.sin(a.phaseTime*9));if(f.id===2)speed*=Math.min(1.2,.75+a.phaseTime*.65);if(f.id===3)speed*=.65+.35*Math.abs(Math.sin(a.phaseTime*10));if(f.id===4)speed*=.5+.8*Math.abs(Math.sin(a.phaseTime*15));if(f.id===5)speed*=.85+.2*Math.sin(a.phaseTime*7);if(f.id===6)speed*=.8+.25*Math.abs(Math.sin(a.phaseTime*12));if(f.id===7)speed*=.8+.3*Math.abs(Math.sin(a.phaseTime*18));if(gap>105)f.x+=f.dir*Math.min(speed*dt,gap-102);f.y+=(o.y-f.y)*Math.min(1,dt*15);f.vy=0;if(Math.abs(f.x-o.x)<=112){a.phase='strike';a.phaseTime=0;this.emit('specialStrike',{i,id:f.id})}}
 else if(a.phase==='strike'){// Follow the target through jumps and evasive movement; only guard or a hit interrupts.
 let gap=Math.abs(f.x-o.x);if(gap>105)f.x+=f.dir*Math.min(900*dt,gap-102);f.y+=(o.y-f.y)*Math.min(1,dt*20);f.vy=0;
 if(a.phaseTime>=m.strike&&Math.abs(f.x-o.x)<=125&&!a.hit){a.hit=true;intents.push({i,j:1-i,m,name:'special',ref:a});a.phase='recover';a.phaseTime=0}}
 else if(a.phase==='sequence'){f.vx=0;o.vx=0;o.vy=0;o.stun=Math.max(o.stun,.12);if(a.phaseTime>=a.nextPart){const n=a.part++,last=n===a.parts.length-1;this.damage(i,1-i,{...m,fixedDamage:a.parts[n],follow:true,final:last,push:last?m.push:0,stun:last?1.1:.2},'special');this.emit('specialBeat',{i,id:f.id,n:n+1,total:a.parts.length,x:o.x,y:o.y});if(last){o.capturedBy=null;a.phase='recover';a.phaseTime=0;this.emit('specialImpact',{i,id:f.id,x:o.x,y:o.y})}else a.nextPart+=m.sequence/(a.parts.length-1)}}
 else if(a.phase==='recover'&&a.phaseTime>=m.recover){f.action=null;f.vy=0}}
 step(dt=DT){if(this.over)return;if(this.intro>0){this.intro=Math.max(0,this.intro-dt);return}if(this.freeze>0){this.freeze-=dt;return}this.t+=dt;if(!this.training&&!this.untimed&&!this.f.some(f=>f.action?.name==='special'))this.time=Math.max(0,this.time-dt);if(this.multiplayer){this.f[1].move=(+this.otherInput.right)-(+this.otherInput.left);this.setBlock(1,this.otherInput.guard)}else this.ai(dt);const p=this.f[0];p.move=(+this.input.right)-(+this.input.left);this.setBlock(0,this.input.guard);let intents=[];
 for(let i=0;i<2;i++){const f=this.f[i],o=this.f[1-i];for(const k of ['stun','down','inv','dodge','dodgeCD','parryCD','parry','counter','flash','wallLock','comboTimer','chainTimer'])f[k]=Math.max(0,f[k]-dt);if(f.comboTimer<=0){f.combo=0;f.comboDamage=0}if(f.buffer){f.buffer.ttl-=dt;if(f.buffer.ttl<=0)f.buffer=null;else if(!f.action&&f.stun<=0&&!f.down&&!f.dodge){let key=f.buffer.key;f.buffer=null;this.command(i,key)}else if(f.action?.connected&&f.action.t>=f.action.m.wind+f.action.m.active&&((f.action.name==='jab'&&f.buffer.key==='punch')||(f.action.name==='cross'&&f.buffer.key==='kick')||f.buffer.key==='special')){let key=f.buffer.key;f.buffer=null;this.command(i,key)}}
 if(!f.action&&f.stun<=0&&f.dodge<=0){f.dir=o.x>=f.x?1:-1;f.stamina=Math.min(100,f.stamina+(f.block?8:23)*dt)}if(f.block){f.guard=Math.max(0,f.guard-7*dt);if(f.guard<=0){f.block=false;f.stun=.6;this.emit('guardbreak',{i})}}else f.guard=Math.min(100,f.guard+(styles[f.id].guardRegen||18)*dt);
 if(f.stun>0||f.down>0)f.block=false;
 if(f.y>0||f.vy>0){f.y+=f.vy*dt;f.vy-=1850*dt;if(f.y<=0){f.y=0;f.vy=0;this.emit('land',{i,x:f.x});if(f.down<=0&&f.stun<=0)f.vx*=.3}}
 if(!f.action&&f.stun<=0&&!f.block&&!f.dodge&&!f.down){f.x+=f.move*styles[f.id].speed*(f.y>0?.7:1)*dt}f.x+=f.vx*dt;if(f.dodge<=0)f.vx*=Math.exp(-8*dt);
 const ac=f.action;if(ac?.name==='special'){this.advanceSpecial(i,dt,intents)}else if(ac){ac.t+=dt;const m=ac.m;if(ac.t>=m.wind&&ac.t<m.wind+m.active&&!ac.hit){const vertical=Math.abs(f.y-o.y)<(ac.name==='upper'?180:100);if(Math.abs(f.x-o.x)<=m.reach+styles[f.id].reach&&vertical){ac.hit=true;intents.push({i,j:1-i,m,name:ac.name})}}
 if(ac.t>=m.wind+m.active&&!ac.checked){ac.checked=true;if(!ac.hit){ac.total+=['kick','heavy','upper','finisher'].includes(ac.name)?.12:.035;this.emit('whiff',{i,name:ac.name})}}
 if(ac.t>=ac.total){f.action=null;f.counter=0}}
 if(f.x<65||f.x>895){f.x=Math.max(65,Math.min(895,f.x));if(Math.abs(f.vx)>230&&f.stun>0&&f.wallLock<=0){f.vx=-f.vx*.55;f.wallLock=1;this.emit('wall',{i,x:f.x})}else f.vx=0}
 }
 let [a,b]=this.f;if(Math.abs(a.x-b.x)<62&&Math.abs(a.y-b.y)<115){let d=a.x<=b.x?1:-1,over=(62-Math.abs(a.x-b.x))/2;a.x-=d*over;b.x+=d*over;a.x=Math.max(65,Math.min(895,a.x));b.x=Math.max(65,Math.min(895,b.x))}
 for(const shot of this.shots){shot.x+=shot.vx*dt;shot.ttl-=dt;let b=this.f[1-shot.i];if(Math.abs(shot.x-b.x)<50&&Math.abs(b.y-shot.y+95)<100){shot.ttl=0;intents.push({i:shot.i,j:1-shot.i,m:shot.m,name:'special'})}}this.shots=this.shots.filter(s=>s.ttl>0&&s.x>0&&s.x<960);
 // A landed normal attack interrupts a super, including on its impact frame.
 for(const h of intents.filter(h=>h.name!=='special'))this.damage(h.i,h.j,h.m,h.name);
 const supers=intents.filter(h=>h.name==='special'&&this.f[h.i].action===h.ref);
 if(supers.length===2){for(const f of this.f){f.action=null;f.stun=.35;f.vx=-f.dir*180}this.freeze=.12;this.emit('specialClash')}
 else for(const h of supers){const f=this.f[h.i],o=this.f[h.j],ac=h.ref,m=h.m;const chain=o.stun>0&&f.comboTimer>0,nextCombo=chain?f.combo+1:1,counter=!!o.action&&(o.action.name==='special'||o.action.t<o.action.m.wind);const total=Math.min(o.hp,Math.round(m.damage*Math.max(.48,1-(nextCombo-1)*.12)*(counter?(styles[f.id].counter||1.15):1)));const parts=Array.from({length:m.hits},(_,n)=>Math.floor(total/m.hits)+(n===m.hits-1?total%m.hits:0));
 if(this.damage(h.i,h.j,{...m,fixedDamage:parts[0],final:m.hits===1,push:m.hits===1?m.push:0,stun:m.hits===1?1.1:m.sequence+.15},'special')){this.emit('specialBeat',{i:h.i,id:f.id,n:1,total:m.hits,x:o.x,y:o.y});if(m.hits>1){o.capturedBy=h.i;ac.phase='sequence';ac.phaseTime=0;ac.parts=parts;ac.part=1;ac.nextPart=m.sequence/(m.hits-1)}else this.emit('specialImpact',{i:h.i,id:f.id,x:o.x,y:o.y})}
 else if(f.action===ac){ac.phase='recover';ac.phaseTime=0;this.emit('specialBlocked',{i:h.i})}}
 if(this.training){for(const f of this.f)if(f.hp<=0){f.hp=140;f.stun=.5;f.inv=.6}return}
 if(a.hp<=0||b.hp<=0){this.over=true;this.winner=a.hp===b.hp?-1:a.hp>b.hp?0:1;this.emit('ko',{winner:this.winner})}else if(this.overtime&&a.hp!==b.hp&&!this.f.some(f=>f.capturedBy!==null)){this.over=true;this.winner=a.hp>b.hp?0:1;this.emit('ko',{winner:this.winner})}else if(!this.untimed&&this.time<=0){if(a.hp===b.hp&&!this.overtime){this.overtime=true;this.time=15;this.emit('overtime')}else{this.over=true;this.winner=a.hp===b.hp?-1:a.hp>b.hp?0:1;this.emit('ko',{winner:this.winner})}}
 }
}
return{Match,moves,styles,specials,ladderDifficulty,aiProfile,DT,GROUND,version:'7.0'};})();
if(typeof module!=='undefined')module.exports=Combat;

// Authoritative rooms and a public directory share the existing ROOMS namespace.
const VERSION='7.0',DIR='__public_directory_62';
const json=(data,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
const validName=(s,min=2,max=20)=>typeof s==='string'&&s.trim().length>=min&&s.trim().length<=max&&/^[\p{L}\p{N} _.'!?-]+$/u.test(s.trim());
const validSettings=s=>s&&validName(s.name,3,32)&&[0,30,45,60].includes(s.seconds)&&typeof s.specials==='boolean'&&['public','private'].includes(s.visibility);
export class DuelRoom{
 constructor(ctx,env){this.ctx=ctx;this.env=env;this.players=[null,null];this.phase='waiting';this.round=1;this.wins=[0,0];this.timer=null;this.expires=Date.now()+15*60000;this.match=null;this.frame=0;this.wait=0;this.last=0;this.acc=0;this.stage=0;this.closed=false;this.settings=null;this.code='';this.hostTicket='';this.lastListing=0;ctx.blockConcurrencyWhile(async()=>{const s=await ctx.storage.get('room');if(s){Object.assign(this,s);if(Date.now()>this.expires)this.closed=true}})}
 directory(path,body){const obj=this.env.ROOMS.get(this.env.ROOMS.idFromName(DIR));return obj.fetch('https://internal/directory/'+path,{method:'POST',body:JSON.stringify(body)})}
 async directoryFetch(request,path){
 const now=Date.now();
 if(path==='list'){const rows=await this.ctx.storage.list({prefix:'r:'}),rooms=[];for(const [k,r] of rows){if(r.expires<now){await this.ctx.storage.delete(k);continue}rooms.push(r)}return json({rooms:rooms.sort((a,b)=>b.created-a.created).slice(0,100),version:VERSION})}
 const d=await request.json();
 if(path==='publish'){if(!/^[A-F0-9]{8}$/.test(d.code))return json({},400);if(!d.room)await this.ctx.storage.delete('r:'+d.code);else await this.ctx.storage.put('r:'+d.code,d.room);return json({ok:true})}
 if(path==='create'){const id=typeof d.requestId==='string'&&/^[a-f0-9-]{36}$/i.test(d.requestId)?d.requestId:null;const key=id?'request:'+d.client+':'+id:null;this.creating??=new Map();if(key&&this.creating.has(key))return (await this.creating.get(key)).clone();const job=this.createRoom(d,now,key);if(key)this.creating.set(key,job);try{return (await job).clone()}finally{if(key)this.creating.delete(key)}}return json({},404)}
 async createRoom(d,now,requestKey){if(requestKey){const saved=await this.ctx.storage.get(requestKey);if(saved&&saved.expires>now)return json(saved.result)}
 if(!validSettings(d.settings))return json({message:'Confira nome, tempo, especial e privacidade da sala.'},400);
 const key='limit:'+d.client,rate=await this.ctx.storage.get(key)||{at:now,n:0};if(now-rate.at>600000){rate.at=now;rate.n=0}if(rate.n>=12)return json({message:'Muitas salas criadas. Aguarde alguns minutos.'},429);rate.n++;await this.ctx.storage.put(key,rate);await this.ctx.storage.setAlarm(now+900000);
 let result;for(let i=0;i<3;i++){const code=[...crypto.getRandomValues(new Uint8Array(4))].map(n=>n.toString(16).padStart(2,'0')).join('').toUpperCase(),ticket=crypto.randomUUID();const obj=this.env.ROOMS.get(this.env.ROOMS.idFromName(code));const r=await obj.fetch('https://internal/init',{method:'POST',body:JSON.stringify({code,hostTicket:ticket,settings:{...d.settings,name:d.settings.name.trim()}})});if(r.ok){result={code,hostTicket:ticket,settings:d.settings};break}}if(result&&requestKey)await this.ctx.storage.put(requestKey,{result,expires:now+900000});return result?json(result):json({message:'Não foi possível criar a sala. Tente novamente.'},503)}
 async alarm(){const now=Date.now();for(const prefix of ['limit:','r:','request:']){const rows=await this.ctx.storage.list({prefix});for(const [k,v] of rows)if(prefix==='limit:'?now-v.at>600000:v.expires<now)await this.ctx.storage.delete(k)}}
 async fetch(request){const u=new URL(request.url);if(u.pathname.startsWith('/directory/'))return this.directoryFetch(request,u.pathname.split('/').pop());
 if(u.pathname==='/init'){if(this.settings)return json({},409);const d=await request.json();if(!validSettings(d.settings))return json({},400);this.code=d.code;this.settings=d.settings;this.hostTicket=d.hostTicket;await this.ctx.storage.put('room',{code:this.code,settings:this.settings,hostTicket:this.hostTicket,expires:this.expires});return json({ok:true})}
 this.sweep(Date.now());if(!this.settings||this.closed||Date.now()>this.expires)return json({message:'Sala não encontrada ou expirada.'},404);
 if(u.pathname==='/info')return json({code:this.code,settings:this.settings,phase:this.phase,available:this.phase==='waiting'&&!this.players[1]&&!!this.players[0]?.hello&&(this.players[0].connected||Date.now()<this.players[0].graceUntil)});
 if(request.headers.get('Upgrade')?.toLowerCase()!=='websocket')return new Response('WebSocket required',{status:426});
 const token=u.searchParams.get('resume');let player=token?this.players.find(p=>p?.resumeToken===token):null;if(token&&!player)return json({message:'Retorno expirado.'},403);if(this.phase!=='waiting')return json({message:'Duelo já iniciado.'},409);
 if(!player){const host=u.searchParams.get('host')===this.hostTicket,seat=host?0:1;if(this.players[seat])return json({message:'Sala cheia.'},409);if(!host&&(!this.players[0]?.hello||(!this.players[0].connected&&Date.now()>this.players[0].graceUntil)))return json({message:'O criador ainda não está disponível.'},409);player={seat,ws:null,fighter:0,name:'Jogador',hello:false,ready:false,inputs:{left:false,right:false,guard:false},count:0,window:Date.now(),lastSeq:-1,lastSeen:Date.now(),resumeToken:crypto.randomUUID(),connected:false,suspended:false,graceUntil:0};this.players[seat]=player}
 const pair=new WebSocketPair(),[client,ws]=Object.values(pair);ws.accept();const old=player.ws;Object.assign(player,{ws,connected:true,suspended:false,graceUntil:0,lastSeen:Date.now(),lastSeq:-1});if(old)try{old.close(1000,'Conexão restaurada')}catch{}
 ws.addEventListener('message',e=>{if(player.ws===ws)this.message(player,e.data)});ws.addEventListener('close',()=>this.disconnect(player,ws));ws.addEventListener('error',()=>this.disconnect(player,ws));this.send(player,{type:'seat',seat:player.seat,resumeToken:player.resumeToken});this.broadcastLobby();this.startTimer();return new Response(null,{status:101,webSocket:client})}
 send(p,d){if(!p?.connected||!p.ws)return;try{p.ws.send(JSON.stringify(d))}catch{this.disconnect(p)}}broadcast(d){for(const p of [...this.players])this.send(p,d)}
 listing(){if(!this.settings)return;const host=this.players[0],room=this.settings.visibility==='public'&&this.phase==='waiting'&&!this.closed&&host?.hello&&(host.connected||Date.now()<host.graceUntil)&&!this.players[1]?{code:this.code,settings:this.settings,host:host.name,fighter:host.fighter,created:this.expires-900000,expires:Math.min(this.expires,Date.now()+150000)}:null;this.listingQueue=(this.listingQueue||Promise.resolve()).catch(()=>{}).then(async()=>{try{const r=await this.directory('publish',{code:this.code,room});if(!r.ok)throw Error('directory');if(room)this.send(this.players[0],{type:'listing',ok:true})}catch{if(room)this.send(this.players[0],{type:'listing',ok:false});this.lastListing=Date.now()}});this.ctx.waitUntil(this.listingQueue);this.lastListing=Date.now()}
 broadcastLobby(){this.broadcast({type:'lobby',settings:this.settings,code:this.code,players:this.players.map(p=>p?{name:p.name,fighter:p.fighter,ready:p.ready,connected:p.connected,away:p.suspended,hello:p.hello}:null),phase:this.phase});this.listing()}
 message(p,raw){if(typeof raw!=='string'||raw.length>1500){p.ws.close(1008,'Mensagem inválida');return}const now=Date.now();p.lastSeen=now;if(now-p.window>=1000){p.window=now;p.count=0}if(++p.count>160){p.ws.close(1008,'Limite de comandos');return}let d;try{d=JSON.parse(raw)}catch{return}if(!d||typeof d!=='object')return;
 if(d.type==='leave'){this.remove(p);return}if(d.type==='ping'){this.send(p,{type:'pong',time:d.time});return}
 if(['suspend','resume'].includes(d.type)&&this.phase==='waiting'){p.suspended=d.type==='suspend';if(p.suspended&&this.settings.visibility==='private'&&p.seat===1)p.ready=false;this.broadcastLobby();return}
 if(d.type==='hello'&&this.phase==='waiting'){if(d.protocol!==VERSION){this.send(p,{type:'error',message:'Atualize o jogo para a versão 7.0 e entre novamente.'});return}if(!Number.isInteger(d.fighter)||d.fighter<0||d.fighter>=Combat.styles.length||!validName(d.name))return;p.fighter=d.fighter;p.name=d.name.trim();p.hello=true;p.ready=p.seat===0||this.settings.visibility==='public';this.broadcastLobby();return}
 if(d.type==='ready'&&this.phase==='waiting'&&p.hello&&!p.suspended){p.ready=true;this.broadcastLobby();return}
 if(d.type==='start'&&p.seat===0&&this.phase==='waiting'){if(this.players.every(x=>x?.ready&&x.hello&&x.connected&&!x.suspended))this.begin();else this.send(p,{type:'error',message:'Aguarde os dois jogadores estarem prontos.'});return}
 if(d.type==='rematch'&&this.phase==='finished'){p.ready=true;this.broadcastLobby();if(this.players.every(x=>x?.ready&&x.connected))this.begin();return}
 if(d.type!=='input'||this.phase!=='fight'||!Number.isSafeInteger(d.seq)||d.seq<=p.lastSeq)return;p.lastSeq=d.seq;if(!d.keys||!['left','right','guard'].every(k=>typeof d.keys[k]==='boolean'))return;Object.assign(p.inputs,{left:d.keys.left,right:d.keys.right,guard:d.keys.guard});Object.assign(p.seat===0?this.match.input:this.match.otherInput,p.inputs);if(['punch','kick','heavy','upper','jump','dodge','special'].includes(d.command))this.match.command(p.seat,d.command)}
 begin(){this.presentationShown=false;this.round=1;this.wins=[0,0];this.stage=crypto.getRandomValues(new Uint32Array(1))[0]%6;this.expires=Date.now()+6*3600000;for(const p of this.players){p.ready=false;p.inputs={left:false,right:false,guard:false}}this.newRound();this.listing();this.startTimer()}
 newRound(){this.match=new Combat.Match(this.players[0].fighter,this.players[1].fighter,{seed:crypto.getRandomValues(new Uint32Array(1))[0],multiplayer:true,roundSeconds:this.settings.seconds,specials:this.settings.specials,introSeconds:this.presentationShown?0:4.2});this.presentationShown=true;this.phase='fight';this.frame=0;this.wait=0;this.players.forEach(p=>p.inputs={left:false,right:false,guard:false});this.broadcast({type:'start',settings:this.settings,stage:this.stage,round:this.round,wins:this.wins,players:this.players.map(p=>({fighter:p.fighter,name:p.name})),snapshot:this.snapshot()})}
 snapshot(){const m=this.match;return{f:m.f,time:m.time,untimed:m.untimed,specials:m.specials,introDuration:m.introDuration,t:m.t,freeze:m.freeze,shots:m.shots,over:m.over,winner:m.winner,overtime:m.overtime,intro:m.intro,roundDamage:m.roundDamage,seed:m.seed,input:m.input,otherInput:m.otherInput}}
 startTimer(){if(this.timer)return;this.last=Date.now();this.acc=0;this.timer=setInterval(()=>this.tick(),1000/60)}stopTimer(){if(this.timer)clearInterval(this.timer);this.timer=null}
 tick(){const now=Date.now();this.sweep(now);if(this.closed)return;if(now>this.expires){this.end('A sala expirou.');return}if(this.phase==='waiting'&&now-this.lastListing>15000)this.listing();this.acc+=Math.min(.1,(now-this.last)/1000);this.last=now;if(['waiting','finished'].includes(this.phase)){this.acc=0;return}let steps=0;while(this.acc>=Combat.DT&&steps++<6){this.acc-=Combat.DT;if(this.phase==='round'){this.wait-=Combat.DT;if(this.wait<=0){if(Math.max(...this.wins)>=2){this.phase='finished';this.players.forEach(p=>p.ready=false);this.broadcast({type:'result',winner:this.wins[0]===2?0:1,wins:this.wins});return}if(this.match.winner>=0)this.round++;this.newRound()}continue}if(this.phase!=='fight')continue;this.match.step();this.frame++;if(this.match.over){const w=this.match.winner;if(w>=0)this.wins[w]++;this.phase='round';this.wait=3.9;this.broadcast({type:'snapshot',snapshot:this.snapshot(),events:this.match.events,round:this.round,wins:this.wins,phase:this.phase});this.match.events=[];break}if(this.frame%2===0){this.broadcast({type:'snapshot',snapshot:this.snapshot(),events:this.match.events,round:this.round,wins:this.wins,phase:this.phase});this.match.events=[]}}}
 sweep(now){for(const p of [...this.players]){if(!p)continue;if(!p.connected){if(this.phase==='waiting'&&now>p.graceUntil)this.remove(p);continue}const limit=this.phase==='waiting'?(p.suspended?120000:60000):15000;if(now-p.lastSeen>limit){const ws=p.ws;this.disconnect(p,ws);try{ws.close(1000,'Conexão inativa')}catch{}}}}
 disconnect(p,ws=p.ws){if(!p||!this.players.includes(p)||!p.connected||p.ws!==ws)return;if(this.phase==='waiting'){Object.assign(p,{connected:false,ws:null,suspended:false,graceUntil:Date.now()+120000});this.broadcastLobby();return}this.end('O adversário saiu ou perdeu a conexão. O duelo foi encerrado.')}
 remove(p){if(!this.players.includes(p))return;if(p.seat===0||this.phase!=='waiting'){this.end('O criador ou o adversário saiu. A sala foi encerrada.');return}this.players[1]=null;p.connected=false;try{p.ws?.close(1000,'Saída da sala')}catch{}this.broadcastLobby()}
 end(message){if(this.closed)return;this.closed=true;this.phase='closed';this.stopTimer();this.listing();this.ctx.waitUntil(this.ctx.storage.put('room',{code:this.code,settings:this.settings,hostTicket:this.hostTicket,expires:0}));for(const p of this.players)if(p)try{p.ws?.send(JSON.stringify({type:'ended',message}));p.ws?.close(1000,'Duelo encerrado')}catch{}this.players=[null,null]}
}
export default{async fetch(request,env){const u=new URL(request.url);if(u.pathname==='/health')return json({ok:true,version:VERSION,release:'7.0.2'});const directory=()=>env.ROOMS.get(env.ROOMS.idFromName(DIR));
 if(u.pathname==='/rooms'&&request.method==='GET')return directory().fetch('https://internal/directory/list');
 if(u.pathname==='/rooms'&&request.method==='POST'){let raw=await request.text();if(raw.length>2048)return json({message:'Dados inválidos.'},413);let settings;try{settings=JSON.parse(raw)}catch{return json({},400)}if(!validSettings(settings))return json({message:'Configurações inválidas.'},400);const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(request.headers.get('CF-Connecting-IP')||'local'));const requestId=settings.requestId;settings={name:settings.name,seconds:settings.seconds,specials:settings.specials,visibility:settings.visibility};const client=[...new Uint8Array(hash)].map(n=>n.toString(16).padStart(2,'0')).join('');return directory().fetch('https://internal/directory/create',{method:'POST',body:JSON.stringify({settings,client,requestId})})}
 const info=u.pathname.match(/^\/rooms\/([A-F0-9]{8})$/),room=u.pathname.match(/^\/room\/([A-F0-9]{8})$/);if(!info&&!room)return json({},404);const code=(info||room)[1],obj=env.ROOMS.get(env.ROOMS.idFromName(code));return info?obj.fetch('https://internal/info'):obj.fetch(request)}};
